// coupang-geo-gamification-fe/pages/product/index.vue
<template>
  <section class="flex flex-col p-4 w-full">
    <h1 class="text-4xl font-bold py-4">What your neighbours are buying</h1>
    <div class="flex flex-row h-full">
      <ProductsList :dongList="dongData" />
      <SeoulMap :dongList="dongData" />
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import ProductsList from "@/components/ProductList.vue";
import SeoulMap from "@/components/SeoulMap.vue";
import dongData from "@/assets/data/seoulDongNow.json";

onMounted(() => {
  console.log(dongData);
});
</script>

<style scoped></style>

// coupang-geo-gamification/src/app/product/page.tsx
"use client";

import React, { useEffect } from "react";
import ProductsList from "@/components/ProductsList";
import dongData from "@/assets/data/seoulDongNow.json";
import SeoulMap from "@/components/SeoulMap";

const Page = () => {
  useEffect(() => {}, []);

  return (
    <section className="flex flex-col p-4">
      <h1 className="text-4xl font-bold py-4">
        What your neighbours are buying
      </h1>
      <div className="flex flex-row h-full">
        <ProductsList dongList={dongData} />
        <SeoulMap dongList={dongData} />
      </div>
    </section>
  );
};
export default Page;
